// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const VERSION = 1
const { c } = require('hyperschema/runtime')

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @roombase/writer
const encoding0 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode (state, m) {
    c.buffer.encode(state, m.key)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @roombase/invite
const encoding1 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode (state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @roombase/metadata
const encoding2 = {
  preencode (state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    state.end++ // max flag is 1 so always one byte

    if (m.messageCount) c.int.preencode(state, m.messageCount)
  },
  encode (state, m) {
    const flags = m.messageCount ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.uint.encode(state, flags)

    if (m.messageCount) c.int.encode(state, m.messageCount)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      createdAt: r2,
      messageCount: (flags & 1) !== 0 ? c.int.decode(state) : 0
    }
  }
}

// @roombase/messages
const encoding3 = {
  preencode (state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.content)
    c.string.preencode(state, m.sender)
    c.int.preencode(state, m.timestamp)
    state.end++ // max flag is 8 so always one byte

    if (m.attachments) c.string.preencode(state, m.attachments)
  },
  encode (state, m) {
    const flags =
      (m.system ? 1 : 0) |
      (m.received ? 2 : 0) |
      (m.hasAttachments ? 4 : 0) |
      (m.attachments ? 8 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.content)
    c.string.encode(state, m.sender)
    c.int.encode(state, m.timestamp)
    c.uint.encode(state, flags)

    if (m.attachments) c.string.encode(state, m.attachments)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      content: r1,
      sender: r2,
      timestamp: r3,
      system: (flags & 1) !== 0,
      received: (flags & 2) !== 0,
      hasAttachments: (flags & 4) !== 0,
      attachments: (flags & 8) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@roombase/writer': return encoding0
    case '@roombase/invite': return encoding1
    case '@roombase/metadata': return encoding2
    case '@roombase/messages': return encoding3
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
