// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const VERSION = 1
import { c } from 'hyperschema/runtime'

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @userbase/writer
const encoding0 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode (state, m) {
    c.buffer.encode(state, m.key)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @userbase/invite
const encoding1 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode (state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @userbase/metadata
const encoding2 = {
  preencode (state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.status)
    c.string.preencode(state, m.seed)
    state.end++ // max flag is 2 so always one byte

    if (m.contacts) c.string.preencode(state, m.contacts)
    if (m.rooms) c.string.preencode(state, m.rooms)
  },
  encode (state, m) {
    const flags =
      (m.contacts ? 1 : 0) |
      (m.rooms ? 2 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.string.encode(state, m.status)
    c.string.encode(state, m.seed)
    c.uint.encode(state, flags)

    if (m.contacts) c.string.encode(state, m.contacts)
    if (m.rooms) c.string.encode(state, m.rooms)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      status: r2,
      seed: r3,
      contacts: (flags & 1) !== 0 ? c.string.decode(state) : null,
      rooms: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @userbase/writer/hyperdb#0
const encoding3 = {
  preencode (state, m) {

  },
  encode (state, m) {

  },
  decode (state) {
    return {
      key: null
    }
  }
}

// @userbase/invite/hyperdb#1
const encoding4 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode (state, m) {
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode (state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @userbase/metadata/hyperdb#2
const encoding5 = {
  preencode (state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.status)
    c.string.preencode(state, m.seed)
    state.end++ // max flag is 2 so always one byte

    if (m.contacts) c.string.preencode(state, m.contacts)
    if (m.rooms) c.string.preencode(state, m.rooms)
  },
  encode (state, m) {
    const flags =
      (m.contacts ? 1 : 0) |
      (m.rooms ? 2 : 0)

    c.string.encode(state, m.name)
    c.string.encode(state, m.status)
    c.string.encode(state, m.seed)
    c.uint.encode(state, flags)

    if (m.contacts) c.string.encode(state, m.contacts)
    if (m.rooms) c.string.encode(state, m.rooms)
  },
  decode (state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      status: r2,
      seed: r3,
      contacts: (flags & 1) !== 0 ? c.string.decode(state) : null,
      rooms: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@userbase/writer': return encoding0
    case '@userbase/invite': return encoding1
    case '@userbase/metadata': return encoding2
    case '@userbase/writer/hyperdb#0': return encoding3
    case '@userbase/invite/hyperdb#1': return encoding4
    case '@userbase/metadata/hyperdb#2': return encoding5
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
